/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ricky.sutjipto_uts;

import javax.swing.JOptionPane;

/**
 *
 * @author ricky
 */
public class kalkulator extends javax.swing.JFrame {
    String bilangan = "";
    double jumlah,bil1,bil2;
    int pilih;
    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_layar = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_hapus = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_koma = new javax.swing.JButton();
        button_kali = new javax.swing.JButton();
        button_samadengan = new javax.swing.JButton();
        button_tambah = new javax.swing.JButton();
        button_kurang = new javax.swing.JButton();
        button_bagi = new javax.swing.JButton();
        button_persen = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textarea_layar.setColumns(20);
        textarea_layar.setRows(5);
        jScrollPane1.setViewportView(textarea_layar);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        button_7.setText("7");
        button_7.setMaximumSize(new java.awt.Dimension(70, 70));
        button_7.setMinimumSize(new java.awt.Dimension(70, 70));
        button_7.setPreferredSize(new java.awt.Dimension(70, 70));
        button_7.setSize(new java.awt.Dimension(70, 70));
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_8.setText("8");
        button_8.setMaximumSize(new java.awt.Dimension(70, 70));
        button_8.setMinimumSize(new java.awt.Dimension(70, 70));
        button_8.setPreferredSize(new java.awt.Dimension(70, 70));
        button_8.setSize(new java.awt.Dimension(70, 70));
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_9.setText("9");
        button_9.setMaximumSize(new java.awt.Dimension(70, 70));
        button_9.setMinimumSize(new java.awt.Dimension(70, 70));
        button_9.setPreferredSize(new java.awt.Dimension(70, 70));
        button_9.setSize(new java.awt.Dimension(70, 70));
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        button_4.setText("4");
        button_4.setMaximumSize(new java.awt.Dimension(70, 70));
        button_4.setMinimumSize(new java.awt.Dimension(70, 70));
        button_4.setPreferredSize(new java.awt.Dimension(70, 70));
        button_4.setSize(new java.awt.Dimension(70, 70));
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_5.setText("5");
        button_5.setMaximumSize(new java.awt.Dimension(70, 70));
        button_5.setMinimumSize(new java.awt.Dimension(70, 70));
        button_5.setPreferredSize(new java.awt.Dimension(70, 70));
        button_5.setSize(new java.awt.Dimension(70, 70));
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_6.setText("6");
        button_6.setMaximumSize(new java.awt.Dimension(70, 70));
        button_6.setMinimumSize(new java.awt.Dimension(70, 70));
        button_6.setPreferredSize(new java.awt.Dimension(70, 70));
        button_6.setSize(new java.awt.Dimension(70, 70));
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_1.setText("1");
        button_1.setMaximumSize(new java.awt.Dimension(70, 70));
        button_1.setMinimumSize(new java.awt.Dimension(70, 70));
        button_1.setPreferredSize(new java.awt.Dimension(70, 70));
        button_1.setSize(new java.awt.Dimension(70, 70));
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setText("2");
        button_2.setMaximumSize(new java.awt.Dimension(70, 70));
        button_2.setMinimumSize(new java.awt.Dimension(70, 70));
        button_2.setPreferredSize(new java.awt.Dimension(70, 70));
        button_2.setSize(new java.awt.Dimension(70, 70));
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_3.setText("3");
        button_3.setMaximumSize(new java.awt.Dimension(70, 70));
        button_3.setMinimumSize(new java.awt.Dimension(70, 70));
        button_3.setPreferredSize(new java.awt.Dimension(70, 70));
        button_3.setSize(new java.awt.Dimension(70, 70));
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_hapus.setText("C");
        button_hapus.setMaximumSize(new java.awt.Dimension(70, 70));
        button_hapus.setMinimumSize(new java.awt.Dimension(70, 70));
        button_hapus.setPreferredSize(new java.awt.Dimension(70, 70));
        button_hapus.setSize(new java.awt.Dimension(70, 70));
        button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hapusActionPerformed(evt);
            }
        });

        button_0.setText("0");
        button_0.setMaximumSize(new java.awt.Dimension(70, 70));
        button_0.setMinimumSize(new java.awt.Dimension(70, 70));
        button_0.setPreferredSize(new java.awt.Dimension(70, 70));
        button_0.setSize(new java.awt.Dimension(70, 70));
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_koma.setText(",");
        button_koma.setMaximumSize(new java.awt.Dimension(70, 70));
        button_koma.setMinimumSize(new java.awt.Dimension(70, 70));
        button_koma.setPreferredSize(new java.awt.Dimension(70, 70));
        button_koma.setSize(new java.awt.Dimension(70, 70));

        button_kali.setText("X");
        button_kali.setMaximumSize(new java.awt.Dimension(70, 70));
        button_kali.setMinimumSize(new java.awt.Dimension(70, 70));
        button_kali.setPreferredSize(new java.awt.Dimension(70, 70));
        button_kali.setSize(new java.awt.Dimension(70, 70));
        button_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kaliActionPerformed(evt);
            }
        });

        button_samadengan.setText("=");
        button_samadengan.setMaximumSize(new java.awt.Dimension(70, 70));
        button_samadengan.setMinimumSize(new java.awt.Dimension(70, 70));
        button_samadengan.setPreferredSize(new java.awt.Dimension(70, 70));
        button_samadengan.setSize(new java.awt.Dimension(70, 70));
        button_samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_samadenganActionPerformed(evt);
            }
        });

        button_tambah.setText("+");
        button_tambah.setMaximumSize(new java.awt.Dimension(70, 70));
        button_tambah.setMinimumSize(new java.awt.Dimension(70, 70));
        button_tambah.setPreferredSize(new java.awt.Dimension(70, 70));
        button_tambah.setSize(new java.awt.Dimension(70, 70));
        button_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tambahActionPerformed(evt);
            }
        });

        button_kurang.setText("-");
        button_kurang.setMaximumSize(new java.awt.Dimension(70, 70));
        button_kurang.setMinimumSize(new java.awt.Dimension(70, 70));
        button_kurang.setPreferredSize(new java.awt.Dimension(70, 70));
        button_kurang.setSize(new java.awt.Dimension(70, 70));
        button_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kurangActionPerformed(evt);
            }
        });

        button_bagi.setText("/");
        button_bagi.setMaximumSize(new java.awt.Dimension(70, 70));
        button_bagi.setMinimumSize(new java.awt.Dimension(70, 70));
        button_bagi.setPreferredSize(new java.awt.Dimension(70, 70));
        button_bagi.setSize(new java.awt.Dimension(70, 70));
        button_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bagiActionPerformed(evt);
            }
        });

        button_persen.setText("%");
        button_persen.setMaximumSize(new java.awt.Dimension(70, 70));
        button_persen.setMinimumSize(new java.awt.Dimension(70, 70));
        button_persen.setPreferredSize(new java.awt.Dimension(70, 70));
        button_persen.setSize(new java.awt.Dimension(70, 70));
        button_persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_persenActionPerformed(evt);
            }
        });

        button_exit.setText("EXIT");
        button_exit.setMaximumSize(new java.awt.Dimension(70, 70));
        button_exit.setMinimumSize(new java.awt.Dimension(70, 70));
        button_exit.setPreferredSize(new java.awt.Dimension(70, 70));
        button_exit.setSize(new java.awt.Dimension(70, 70));
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_kali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_koma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_bagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_persen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_kali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_bagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_persen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_koma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Anda akan menutup program");
        System.exit(0);
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hapusActionPerformed
        // TODO add your handling code here:
        textarea_layar.setText("");
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        bilangan="";
    }//GEN-LAST:event_button_hapusActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
        // TODO add your handling code here:
        bilangan +="0";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_0ActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        // TODO add your handling code here:
        bilangan +="1";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        // TODO add your handling code here:
        bilangan +="2";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
        // TODO add your handling code here:
        bilangan +="3";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
        // TODO add your handling code here:
        bilangan +="4";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        // TODO add your handling code here:
        bilangan +="5";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        // TODO add your handling code here:
        bilangan +="6";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        // TODO add your handling code here:
        bilangan +="7";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
        // TODO add your handling code here:
        bilangan +="8";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        // TODO add your handling code here:
        bilangan +="9";        
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_9ActionPerformed

    private void button_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tambahActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bilangan);
        textarea_layar.setText("+");
        bilangan="";
        pilih=1;      
    }//GEN-LAST:event_button_tambahActionPerformed

    private void button_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kurangActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bilangan);
        textarea_layar.setText("-");
        bilangan="";
        pilih=2;                     
    }//GEN-LAST:event_button_kurangActionPerformed

    private void button_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kaliActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bilangan);
        textarea_layar.setText("x");
        bilangan="";
        pilih=3;  
    }//GEN-LAST:event_button_kaliActionPerformed

    private void button_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bagiActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bilangan);
        textarea_layar.setText("/");
        bilangan="";
        pilih=4;  
    }//GEN-LAST:event_button_bagiActionPerformed

    private void button_persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_persenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_persenActionPerformed

    private void button_samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_samadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1 -> {
            bil2 = Double.parseDouble(String.valueOf(textarea_layar.getText()));
            jumlah = bil1+bil2;
            bilangan = Double.toString(jumlah);
            }
        case 2 -> {
            bil2 =Double.parseDouble(String.valueOf(textarea_layar.getText()));
            jumlah = bil1 - bil2;
            bilangan = Double.toString(jumlah);
            }
        case 3 -> {
            bil2 = Double.parseDouble(String.valueOf(textarea_layar.getText()));
            jumlah = bil1 * bil2;
            bilangan = Double.toString(jumlah);
            }
        case 4 -> {
            bil2 = Double.parseDouble(String.valueOf(textarea_layar.getText()));
            jumlah = bil1 / bil2;
            bilangan = Double.toString(jumlah);
            }
        } 
        textarea_layar.setText(bilangan);
    }//GEN-LAST:event_button_samadenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_bagi;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_hapus;
    private javax.swing.JButton button_kali;
    private javax.swing.JButton button_koma;
    private javax.swing.JButton button_kurang;
    private javax.swing.JButton button_persen;
    private javax.swing.JButton button_samadengan;
    private javax.swing.JButton button_tambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea_layar;
    // End of variables declaration//GEN-END:variables
}
